export { SplashScreen } from './SplashScreen'
export { Navbar } from './Navbar'
export { GameArena } from './GameArena'
export { Profile } from './Profile'
export { Leaderboard } from './Leaderboard'
export { Header } from './Header'
